import os
import json
import logging
import uuid
import asyncio
from typing import List, Optional, Literal, Dict, Any, Union, Annotated
from typing_extensions import TypedDict
from pydantic import BaseModel, Field
from datetime import datetime

# LangChain / LangGraph Imports
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEndpoint
from langgraph.graph import StateGraph, END

# Sandbox Import
from .sandbox import LocalSandbox

logger = logging.getLogger(__name__)

# ==============================================================================
# 0. CONFIGURATION & MODELS
# ==============================================================================

# --- API CLIENTS ---

# 1. PLANNER & SYNTHESIZER: Gemini 1.5 Flash (Fast, Long Context)
# Falls back to standard generative AI if key is set
gemini_llm = None
if os.getenv("GEMINI_API_KEY"):
    try:
        gemini_llm = ChatGoogleGenerativeAI(
            model="gemini-1.5-flash",
            temperature=0.3,
            google_api_key=os.getenv("GEMINI_API_KEY"),
            convert_system_message_to_human=True
        )
    except Exception as e:
        logger.error(f"Gemini Init Error: {e}")

# 2. CODER & ENGINEER: Groq Llama-3-70b (Fast Inference, Logic)
groq_llm = None
if os.getenv("GROQ_API_KEY"):
    groq_llm = ChatGroq(
        model="llama3-70b-8192", 
        temperature=0.1,
        groq_api_key=os.getenv("GROQ_API_KEY")
    )

# 3. SPECIALIST / FALLBACK: HuggingFace
hf_llm = None
if os.getenv("HF_TOKEN"):
    try:
        hf_llm = HuggingFaceEndpoint(
            repo_id="mistralai/Mistral-7B-Instruct-v0.2",
            task="text-generation",
            max_new_tokens=512,
            do_sample=False,
            huggingfacehub_api_token=os.getenv("HF_TOKEN")
        )
    except Exception as e:
        logger.warning(f"HF Output init failed: {e}")

# ==============================================================================
# 1. DATA MODELS (Aligned with AntigravityNotebookUI.xml)
# ==============================================================================

# --- Internal Thought Process ---
class PlanStep(BaseModel):
    step_number: int
    activity: str
    rationale: str

class AnalystPlan(BaseModel):
    """The 'Architect's Blueprint' generated by Gemini"""
    objective_understanding: str
    steps: List[PlanStep]
    data_requirements: List[str]
    potential_challenges: List[str]

class CodingTask(BaseModel):
    """The 'Engineering Task' generated by Groq"""
    python_code: str = Field(description="Executable pandas code. MUST define 'metrics' dict and use plt.show() or plt.savefig().")
    explanation: str

class InsightContent(BaseModel):
    summary: str
    key_evidence: List[str]
    notable_examples: List[str]
    implications: List[str]
    confidence: Literal["high", "medium", "low"]

class PinMetadata(BaseModel):
    pin_eligible: bool
    suggested_title: str
    suggested_description: str
    pin_tags: List[str] = Field(default_factory=list)
    source_cells: List[str] = Field(default_factory=list)
    drilldown_path: Dict[str, Any] = Field(default_factory=dict) # e.g. {"type": "notebook", "target_cell_ids": []}

# --- Final Notebook Schema (Per XML) ---
class NotebookCell(BaseModel):
    cell_id: str
    cell_type: Literal['prompt', 'reasoning', 'metric', 'visualization', 'table', 'insight', 'suggestion']
    title: str
    content: Any # JSON object
    dependencies: Dict[str, Any] = Field(default_factory=dict) # {"depends_on": "cell_id"}
    ui_hints: Dict[str, Any] = Field(default_factory=dict) # {"collapsible": bool, "emphasis": str}

class AnalysisMetadata(BaseModel):
    domain: Literal["health", "medical", "life_sciences", "general"]
    analysis_type: Literal["descriptive", "diagnostic", "exploratory", "comparative"]
    generated_at: str
    confidence_level: Literal["high", "medium", "exploratory"]

class NotebookOutput(BaseModel):
    notebook_id: str
    analysis_metadata: AnalysisMetadata
    cells: List[NotebookCell]

# ==============================================================================
# 2. STATE DEFINITION
# ==============================================================================

class AgentState(TypedDict):
    """
    Streaming State. 
    We use strictly typed updates to track the flow.
    """
    user_prompt: str
    dataset_context: Dict[str, Any] # Metadata + Data Preview
    
    # Step 1: Planning (Gemini)
    plan: Optional[AnalystPlan]
    
    # Step 2: Coding (Groq)
    code_task: Optional[CodingTask]
    
    # Step 3: Execution (Sandbox)
    execution_logs: Optional[str]
    execution_artifacts: Dict[str, Any] # metrics, charts
    execution_success: bool
    execution_error: Optional[str]
    
    # Step 4: Synthesis (Gemini/Groq)
    final_notebook: Optional[NotebookOutput]

# ==============================================================================
# 3. NODES (The "Brains")
# ==============================================================================

def planner_node(state: AgentState):
    """
    Role: ARCHITECT (Gemini)
    Goal: Understands the user request and dataset context. Creates a high-level plan.
    """
    logger.info("--- NODE: PLANNER (GEMINI) ---")
    
    # Use Groq FIRST for speed (Llama-3-70b is very capable planner)
    model = groq_llm or gemini_llm or hf_llm
    if model:
        logger.info(f"PLANNER SELECTED MODEL: {type(model).__name__}")
    else:
        raise ValueError("No AI Model configured!")

    prompt = ChatPromptTemplate.from_template("""
    You are Antigravity, an expert Health Data Analyst.
    
    USER REQUEST: "{user_prompt}"
    
    DATASET CONTEXT:
    {dataset_context}
    
    Your goal is to PLAN a rigorous analysis.
    Do NOT write code yet. Just the "Thought Process".
    
    Output a JSON structure matching 'AnalystPlan' with:
    - objective_understanding
    - steps (rationale)
    - data_requirements
    - potential_challenges
    """)
    
    chain = prompt | model.with_structured_output(AnalystPlan)
    
    try:
        plan = chain.invoke({
            "user_prompt": state["user_prompt"],
            "dataset_context": json.dumps(state["dataset_context"], default=str)[:3000] # Truncate for safety
        })
        return {"plan": plan}
    except Exception as e:
        logger.error(f"Planning failed: {e}")
        # Fallback plan if structured output fails
        return {"plan": AnalystPlan(
            objective_understanding="Analyze data based on request",
            steps=[PlanStep(step_number=1, activity="Analyze Data", rationale="Standard analysis")],
            data_requirements=[],
            potential_challenges=["AI Error"]
        )}

def coder_node(state: AgentState):
    """
    Role: ENGINEER (Groq)
    Goal: Takes the plan and writes efficient Pandas/Matplotlib code.
    """
    logger.info("--- NODE: CODER (GROQ) ---")
    
    # Prefer Groq for coding (Llama-3 is great at Python)
    model = groq_llm or gemini_llm or hf_llm
    
    plan_str = state["plan"].model_dump_json() if state["plan"] else "No plan"
    
    prompt = ChatPromptTemplate.from_template("""
    You are an expert Python Data Engineer.
    
    PLAN:
    {plan}
    
    DATASET PROPERTIES:
    {dataset_context}
    
    TASK: Write Python code to execute this plan.
    RULES:
    1. Assume 'df' is already loaded with the data.
    2. You MUST create a dictionary called 'metrics' for key numbers.
    3. You MUST use plt.show() or simply create plots (the sandbox captures them).
    4. Handle missing data gracefully.
    5. No markdown fencing around the code logic if possible, or simple block.
    
    Output JSON 'CodingTask' with 'python_code' and 'explanation'.
    """)
    
    chain = prompt | model.with_structured_output(CodingTask)
    
    try:
        task = chain.invoke({
            "plan": plan_str,
            "dataset_context": json.dumps(state["dataset_context"], default=str)[:2000]
        })
        return {"code_task": task}
    except Exception as e:
        # Fallback basic code
        logger.error(f"Coding failed: {e}")
        return {"code_task": CodingTask(python_code="print('Error generating code')", explanation="Failed")}

def executor_node(state: AgentState):
    """
    Role: EXECUTOR (Sandbox)
    Goal: Run the code safely.
    """
    logger.info("--- NODE: EXECUTOR (SANDBOX) ---")
    
    code = state["code_task"].python_code if state["code_task"] else ""
    
    # Extract data rows from context hack (passed from app.py)
    data_rows = state["dataset_context"].get("data_rows", [])
    if not data_rows:
        return {
            "execution_success": False, 
            "execution_error": "No data rows provided for execution",
            "execution_logs": "Error: missing data",
            "execution_artifacts": {}
        }
        
    import pandas as pd
    df = pd.DataFrame(data_rows)
    
    sandbox = LocalSandbox()
    result = sandbox.execute(code, df)
    
    return {
        "execution_success": result.success,
        "execution_logs": result.output_log,
        "execution_error": result.error,
        "execution_artifacts": result.artifacts
    }

def synthesis_node(state: AgentState):
    """
    Role: SYNTHESIZER (Gemini/Groq)
    Role: Taking results and formatting into the Antigravity Notebook XML Schema.
    """
    logger.info("--- NODE: SYNTHESIZER ---")
    
    model = gemini_llm or groq_llm
    
    prompt = ChatPromptTemplate.from_template("""
    You are the Antigravity Synthesis Engine.
    
    USER REQUEST: {user_prompt}
    
    PLAN: {plan_summary}
    
    EXECUTION LOGS: {logs}
    METRICS: {metrics}
    
    Construct a Final Analysis Notebook observing the strict SystemContract.
    Return a JSON object matching 'NotebookOutput'.
    
    - Domain: health/medical
    - Confidence: Check metrics
    - Cells: Prompt, Reasoning, Metrics, Visualization (if charts exist), Insight, Suggestion.
    """)
    
    chain = prompt | model.with_structured_output(NotebookOutput)
    
    try:
        final_output = chain.invoke({
            "user_prompt": state["user_prompt"],
            "plan_summary": str(state["plan"].steps) if state["plan"] else "N/A",
            "logs": state["execution_logs"],
            "metrics": str(state["execution_artifacts"].get("metrics", {}))
        })
        
        # Inject chart artifacts manually since LLM can't see the images
        if state["execution_artifacts"].get("chart"):
            # Find viz cell or append one
            chart_b64 = state["execution_artifacts"]["chart"]
            # Look for a placeholder viz cell or create one
            viz_cell = NotebookCell(
                cell_id=f"viz_{uuid.uuid4().hex[:8]}",
                cell_type="visualization",
                title="Generated Visualization",
                content={"chart_type": "image", "data": chart_b64},
                ui_hints={"collapsible": False, "emphasis": "normal"}
            )
            # Insert before insight/suggestion
            final_output.cells.insert(-2, viz_cell) 

        return {"final_notebook": final_output}
        
    except Exception as e:
        logger.error(f"Synthesis failed: {e}")
        return {"execution_error": str(e)}

# ==============================================================================
# 4. GRAPH WIRING
# ==============================================================================

workflow = StateGraph(AgentState)

workflow.add_node("planner", planner_node)
workflow.add_node("coder", coder_node)
workflow.add_node("executor", executor_node)
workflow.add_node("synthesizer", synthesis_node)

workflow.set_entry_point("planner")

workflow.add_edge("planner", "coder")
workflow.add_edge("coder", "executor")

def check_execution(state):
    """Conditional edge: Did execution succeed?"""
    if state["execution_success"]:
        return "synthesizer"
    else:
        # In a real system, we'd loop back to 'coder' to fix bugs (Self-Healing)
        # For V1, we proceed to synthesis to report the error
        return "synthesizer"

workflow.add_conditional_edges("executor", check_execution)
workflow.add_edge("synthesizer", END)

app_graph = workflow.compile()

# ==============================================================================
# 5. STREAMING INTERFACE
# ==============================================================================

async def stream_notebook_generation(user_prompt: str, dataset_context: Dict[str, Any], data_rows: List[Dict]):
    """
    Generator that yields JSON events for the WebSocket.
    Uses 'astream_events' to provide real-time token-level feedback.
    """
    # Prepare initial state
    dataset_context["data_rows"] = data_rows # Inject for executor
    
    inputs = {
        "user_prompt": user_prompt,
        "dataset_context": dataset_context
    }
    
    # Track current active node to know what the token belongs to
    current_node = None
    
    # Use astream_events to catch internal LLM streaming tokens
    async for event in app_graph.astream_events(inputs, version="v1"):
        kind = event["event"]
        
        # 1. NODE ENTRIES - Set Context
        if kind == "on_chain_start":
            node_name = event["name"]
            if node_name == "planner":
                current_node = "planner"
                yield {"type": "status", "phase": "planning", "message": "Architecting analysis plan..."}
            elif node_name == "coder":
                current_node = "coder"
                yield {"type": "status", "phase": "coding", "message": "Engineering Python solution..."}
            elif node_name == "executor":
                current_node = "executor"
                yield {"type": "status", "phase": "execution", "message": "Executing in Sandbox..."}
            elif node_name == "synthesizer":
                current_node = "synthesizer"
                yield {"type": "status", "phase": "synthesis", "message": "Synthesizing final report..."}

        # 2. LLM TOKENS - Stream Content
        elif kind == "on_chat_model_stream":
            content = event["data"]["chunk"].content
            if content:
                # Differentiate based on the active node
                if current_node == "planner":
                    # Stream thought process tokens
                    yield {"type": "token", "target": "thought", "chunk": content}
                elif current_node == "coder":
                    # Stream code tokens
                    yield {"type": "token", "target": "code", "chunk": content}

        # 3. NODE OUTPUTS - Final structural updates (keep these for safety/validation)
        elif kind == "on_chain_end":
            data = event["data"].get("output")
            if not data: continue
            
            node_name = event["name"]
            
            if node_name == "executor":
                 # Execution logs aren't streamed by LLM, so we yield them here
                 yield {
                    "type": "execution",
                    "logs": data.get("execution_logs", ""),
                    "success": data.get("execution_success", False)
                }
            elif node_name == "synthesizer" and "final_notebook" in data:
                 yield {
                    "type": "complete",
                    "payload": data["final_notebook"].model_dump()
                }
            elif node_name == "synthesizer" and "execution_error" in data:
                 yield {
                    "type": "error",
                    "error": data["execution_error"]
                }

