
import os

types_path = r"c:\Users\dell\Desktop\Lab-IQ\src\integrations\supabase\types.ts"
patch_path = r"c:\Users\dell\Desktop\Lab-IQ\src\integrations\supabase\types_patch.ts"

with open(types_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

with open(patch_path, 'r', encoding='utf-8') as f:
    patch_content = f.read()

# Find insertion point: before "bottleneck_comments: {"
insert_idx = -1
for i, line in enumerate(lines):
    if "bottleneck_comments: {" in line:
        insert_idx = i
        break

if insert_idx != -1:
    # Ensure the previous block has a comma if needed, though usually they do.
    # But since we are inserting into a json-like structure in TS types, commas are optional or comma separators used.
    # Looking at the file, it seems to use standard TS object syntax which doesn't strictly enforce commas between properties if newlines exist, 
    # BUT existing code likely has them or missing them. 
    # Actually, in TS type definitions `key: { ... }` usually needs no comma if on separate lines, but `types.ts` generated by supabase USUALLY puts commas.
    # Let's check line 119 in previous view: `      }`. It does NOT have a comma.
    # We should add a generic comma to our patch end or start?
    # Let's add the patch. The patch file content should be clean.
    
    # We will insert the patch content.
    new_lines = lines[:insert_idx] + [patch_content + "\n"] + lines[insert_idx:]
    
    with open(types_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    print("Successfully injected types.")
else:
    print("Could not find insertion point 'bottleneck_comments: {'")
